path

diff --git a/pamb b/pamb
--- a/pamb
+++ b/pamb
@@ -1,10 +1,12 @@
 #!/bin/bash
 
 CMD=$1
-TIMESTAMP=$2
+APP_VERSION=$2
+TIMESTAMP=$3
+NAMESPACE=$4
 
 function print_howto() {
-    echo "How to use : pamb CMD APP_VERSION TIMESTAMP NAMESPACE OTHER_PARAM1 OTHER_PARAM2 (eg. pamb build_demoecommerce 6.0 201906011030 stg)"
+    echo "How to use : pamb CMD APP_VERSION TIMESTAMP NAMESPACE OTHER_PARAM1 OTHER_PARAM2 (eg. pamb build_cms_front 6.0 201906011030 stg)"
 }
 
 if [ "$CMD" = "" ]; then
@@ -13,8 +15,20 @@ if [ "$CMD" = "" ]; then
     exit 1
 fi
 
+if [ "$APP_VERSION" = "" ]; then
+    echo -e "APP_VERSION cannot be blank"
+    print_howto
+    exit 1
+fi
+
 if [ "$TIMESTAMP" = "" ]; then
     echo -e "TIMESTAMP cannot be blank"
+    print_howto
+    exit 1
+fi
+
+if [ "$NAMESPACE" == "" ]; then
+    echo -e "NAMESPACE cannot be blank"
     print_howto
     exit 1
 fi
